scraping:
  user_agent: "ScrapperBot/1.0"     # User-Agent personalizado para solicitudes HTTP
  timeout: 5                        # Tiempo de espera en segundos para las solicitudes
  max_links: 30                     # Número máximo de enlaces a seguir en el scraping

scanner:
  xss_payloads:
    - "<script>alert(1)</script>"
    - "'><img src=x onerror=alert(1)>"
    - "<svg/onload=alert(1)>"
    - "';alert(String.fromCharCode(88,83,83))//"
    - "\";alert('XSS');//"
    - "<img src='javascript:alert(1)'>"
  
  sql_injection_payloads:
    - "' OR '1'='1"
    - "' OR 'a'='a"
    - "' OR 1=1--"
    - "\" OR \"\"=\""
    - "' OR '1'='1' --"
    - "' OR '1'='1' /*"
    - "admin' --"
    - "admin' #"
    - "admin'/*"
  
  # Nuevas vulnerabilidades y configuraciones adicionales
  csp_vulnerability: true           # Verifica la cabecera Content Security Policy
  anti_csrf_token: true             # Verifica la presencia de tokens Anti-CSRF
  anti_clickjacking: true           # Verifica la cabecera Anti-Clickjacking

  # Configuración para la detección de respuestas vulnerables
  detection:
    xss_indicators:
      - "<script>alert(1)</script>"
      - "alert(1)"
      - "<img src=x onerror=alert(1)>"
      - "XSS"
    sql_injection_indicators:
      - "SQL syntax"
      - "sql error"
      - "mysql"
      - "You have an error in your SQL syntax"
      - "Warning: mysql"
      - "Unclosed quotation mark after the character string"
      - "syntax error"
    csp_indicators:
      - "Content-Security-Policy"
    anti_csrf_indicators:
      - "csrf"
    clickjacking_indicators:
      - "X-Frame-Options"

# Parámetros adicionales de escaneo
scan_parameters:
  max_links: 50                     # Máximo de enlaces a seguir en el scraping
  retry_on_failure: true            # Volver a intentar en caso de fallo de conexión
  max_retries: 3                    # Número máximo de reintentos por solicitud fallida
  delay_between_requests: 2         # Retraso en segundos entre cada solicitud



